from pathlib import Path
p=Path('app.py')
s=p.read_text(encoding='utf-8')
needle='''</style>\"\"\",unsafe_allow_html=True)\n    base=json.loads((ROOT/\"config.json\").read_text(encoding=\"utf-8\"))'''
insert='''</style>\"\"\",unsafe_allow_html=True)\n    st.markdown(\"\"\"<style>\n/* AJUSTE FINAL: somente mobile, sem alterar desktop ou a estrutura das colunas. */\n@media(max-width:600px){\n  .st-key-top_nav_buttons .stButton button{\n    box-sizing:border-box!important;\n    width:100%!important;min-width:0!important;max-width:100%!important;\n    padding-left:3px!important;padding-right:3px!important;\n    font-size:clamp(.48rem,2.2vw,.56rem)!important;\n    letter-spacing:-.01em!important;line-height:1!important;\n    white-space:nowrap!important;overflow:hidden!important;text-overflow:clip!important;\n  }\n  .st-key-top_nav_buttons .stButton button p,\n  .st-key-top_nav_buttons .stButton button span{\n    margin:0!important;padding:0!important;max-width:100%!important;\n    font:inherit!important;line-height:1!important;letter-spacing:inherit!important;\n    white-space:nowrap!important;overflow:hidden!important;text-overflow:clip!important;\n  }\n  .st-key-week_nav_buttons .stButton button{\n    box-sizing:border-box!important;\n    padding-left:2px!important;padding-right:2px!important;\n    font-size:clamp(.45rem,2vw,.53rem)!important;\n    line-height:1!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:clip!important;\n  }\n  .st-key-week_nav_buttons .stButton button p,\n  .st-key-week_nav_buttons .stButton button span{\n    margin:0!important;padding:0!important;max-width:100%!important;\n    font:inherit!important;line-height:1!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:clip!important;\n  }\n}\n</style>\"\"\",unsafe_allow_html=True)\n    base=json.loads((ROOT/\"config.json\").read_text(encoding=\"utf-8\"))'''
if needle not in s:
    raise SystemExit('Ponto de insercao nao encontrado')
s=s.replace(needle,insert,1)
p.write_text(s,encoding='utf-8')
print('Ajuste mobile de texto dos botoes aplicado.')
