from pathlib import Path

p=Path('app.py')
s=p.read_text(encoding='utf-8')

# 1) Remove card executivo de zeros.
s=s.replace('        f\'<div class="exec-card secondary critical"><small>ZEROS</small><strong>{zeros}</strong><span>Dias sem venda</span></div>\'\n','')

# 2) Adiciona componentes compactos para performance e produção por canal.
marker='def seller_kpi_card(label,value,sub,cls):\n'
helpers='''def performance_summary_html(counts):\n    items=[\n        ("Azul",counts.get("Azul",0),"#0891B2"),\n        ("Verde",counts.get("Verde",0),"#16A34A"),\n        ("Amarelo",counts.get("Amarelo",0),"#F59E0B"),\n        ("Vermelho",counts.get("Vermelho",0),"#DC2626"),\n    ]\n    chips=''.join(\n        f'<div class="perf-chip" style="--chip:{color}"><span>{label}</span><strong>{value}</strong></div>'\n        for label,value,color in items\n    )\n    return f'<div class="perf-summary">{chips}</div>'\n\ndef channel_summary_html(channels,total):\n    groups=[\n        (("VENDEDORES FRANQUIA",channels.get("VENDEDORES FRANQUIA",0)),("WEBSITE",channels.get("WEBSITE",0))),\n        (("FREELANCE",channels.get("FREELANCE",0)),("CANAL NACIONAL",channels.get("CANAL NACIONAL",0))),\n    ]\n    cards=[]\n    for pair in groups:\n        inner=''.join(\n            f'<div class="channel-mini"><span>{name}</span><strong>{value}</strong><small>{pct(value/total if total else 0)} do total</small></div>'\n            for name,value in pair\n        )\n        cards.append(f'<div class="channel-group">{inner}</div>')\n    return '<div class="channel-summary">'+''.join(cards)+'</div>'\n\n'''
if 'def performance_summary_html' not in s:
    s=s.replace(marker,helpers+marker,1)

# 3) Troca distribuição de performance por um único painel com 4 mini cards.
old='''        st.markdown('<div class="section">Distribuição de performance</div>',unsafe_allow_html=True); counts={k:0 for k in ("Azul","Verde","Amarelo","Vermelho")}\n        for x in team:counts[performance(x["media"])[0]]+=1\n        tones={"Azul":"cyan","Verde":"green","Amarelo":"yellow","Vermelho":"red"}; cards(st,[(k.upper(),v,tones[k],"vendedores") for k,v in counts.items()],4)\n'''
new='''        st.markdown('<div class="section">Distribuição de performance</div>',unsafe_allow_html=True); counts={k:0 for k in ("Azul","Verde","Amarelo","Vermelho")}\n        for x in team:counts[performance(x["media"])[0]]+=1\n        st.markdown(performance_summary_html(counts),unsafe_allow_html=True)\n'''
if old not in s: raise SystemExit('bloco performance não encontrado')
s=s.replace(old,new,1)

# 4) Produção por canal: remove ADM e exibe 2 painéis, 2 indicadores em cada.
old='''        st.markdown('<div class="section">Produção por canal</div>',unsafe_allow_html=True); channels={name:0 for name in ("VENDEDORES FRANQUIA","WEBSITE","ADM","FREELANCE","CANAL NACIONAL")}\n        for item in summary:channels[channel_name(item)]+=item["vendas"]\n        cards(st,[(name,value,"cyan",pct(value/total if total else 0)+" do total") for name,value in channels.items()],5)\n'''
new='''        st.markdown('<div class="section">Produção por canal</div>',unsafe_allow_html=True); channels={name:0 for name in ("VENDEDORES FRANQUIA","WEBSITE","FREELANCE","CANAL NACIONAL")}\n        for item in summary:\n            name=channel_name(item)\n            if name!="ADM" and name in channels:channels[name]+=item["vendas"]\n        st.markdown(channel_summary_html(channels,total),unsafe_allow_html=True)\n'''
if old not in s: raise SystemExit('bloco canais não encontrado')
s=s.replace(old,new,1)

# 5) CSS para os novos blocos e ranking mobile mais compacto.
css='''\n.perf-summary{background:white;border:1px solid var(--line);border-radius:14px;padding:12px;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;box-shadow:0 2px 10px rgba(15,23,42,.04)}.perf-chip{position:relative;border:1px solid #E2E8F0;border-radius:11px;padding:12px 14px;background:#F8FAFC;overflow:hidden}.perf-chip:before{content:"";position:absolute;left:0;top:0;bottom:0;width:5px;background:var(--chip)}.perf-chip span{display:block;font-size:.64rem;font-weight:900;color:#64748B;text-transform:uppercase;letter-spacing:.05em}.perf-chip strong{display:block;font-size:1.65rem;margin-top:6px;color:#0F172A}.channel-summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.channel-group{background:white;border:1px solid var(--line);border-radius:14px;padding:12px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;box-shadow:0 2px 10px rgba(15,23,42,.04)}.channel-mini{border:1px solid #E2E8F0;border-radius:11px;padding:13px 14px;background:#F8FAFC;min-width:0}.channel-mini span{display:block;font-size:.64rem;font-weight:900;color:#64748B;letter-spacing:.04em}.channel-mini strong{display:block;font-size:1.75rem;line-height:1.05;margin-top:7px;color:#0F172A}.channel-mini small{display:block;font-size:.66rem;color:#94A3B8;margin-top:5px}\n@media(max-width:720px){.perf-summary{grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;padding:8px}.perf-chip{padding:10px 11px}.perf-chip strong{font-size:1.4rem}.channel-summary{grid-template-columns:1fr;gap:8px}.channel-group{grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;padding:8px}.channel-mini{padding:10px}.channel-mini strong{font-size:1.4rem}.rank-card{border-radius:12px}.rank-row{grid-template-columns:28px minmax(0,1fr)!important;gap:4px!important;padding:5px 3px!important}.rank-pos{font-size:.72rem}.rank-name{padding:9px!important;border-radius:10px!important;gap:7px!important}.rank-seller{padding-top:0!important;margin-bottom:3px}.rank-seller b{font-size:.9rem!important;line-height:1.15}.rank-seller small{font-size:.57rem!important}.rank-inside{display:grid!important;grid-template-columns:repeat(6,minmax(0,1fr))!important;gap:5px!important}.rank-inside span{grid-column:span 2;min-height:42px!important;padding:5px 3px!important;border-left:0!important;border:1px solid rgba(255,255,255,.18);border-radius:7px;background:rgba(255,255,255,.06)}.rank-inside .main-kpi{grid-column:span 3!important;background:rgba(15,23,42,.20)}.rank-inside .main-kpi strong{font-size:1.55rem!important}.rank-inside .main-kpi small{font-size:.58rem!important;font-weight:800}.rank-inside strong{font-size:.82rem!important;line-height:1.05!important}.rank-inside small{font-size:.49rem!important;margin-top:3px!important}.rank-inside .neo-highlight{grid-column:span 2!important}.rank-inside .total-highlight{grid-column:span 3!important}.rank-inside .total-highlight strong{font-size:.98rem!important}}\n'''
if '.perf-summary{' not in s:
    s=s.replace('</style>',css+'\n</style>',1)

p.write_text(s,encoding='utf-8')
