from pathlib import Path

p=Path('app.py')
s=p.read_text(encoding='utf-8')

old='''    if "area" not in st.session_state:st.session_state.area="VISÃO GERAL"\n    top_left,top_menu=st.columns([18,1])\n    with top_left:st.markdown('<div class="bi-topbar"><h1>PAINEL COMERCIAL — AFOGADOS</h1><p>Visão executiva de produção, performance, histórico e remuneração variável</p></div>',unsafe_allow_html=True)\n    with top_menu:\n        with st.popover("⋮"):\n            st.markdown("**NAVEGAÇÃO**")\n            areas=["VISÃO GERAL","VENDEDORES","SEMANAL","PREMIAÇÕES","GESTÃO"]\n            st.session_state.area=st.radio("Área",areas,index=areas.index(st.session_state.area),label_visibility="collapsed")\n            st.caption("Menu gerencial")\n    area=st.session_state.area\n'''
new='''    areas=["VISÃO GERAL","VENDEDORES","SEMANAL","PREMIAÇÕES","GESTÃO"]\n    if "area" not in st.session_state:st.session_state.area="VISÃO GERAL"\n    requested=st.query_params.get("area")\n    if requested in areas:st.session_state.area=requested\n    area=st.session_state.area\n    import urllib.parse\n    nav=''.join(\n        f'<a class="top-nav-item {"active" if item==area else ""}" href="?area={urllib.parse.quote(item)}">{html.escape(item)}</a>'\n        for item in areas\n    )\n    st.markdown(\n        '<div class="bi-topbar bi-topbar-nav">'\n        '<div class="bi-brand"><h1>PAINEL COMERCIAL — AFOGADOS</h1><p>Visão executiva de produção, performance, histórico e remuneração variável</p></div>'\n        f'<nav class="top-nav">{nav}</nav>'\n        '</div>',unsafe_allow_html=True\n    )\n'''
if old not in s: raise SystemExit('bloco de menu superior não encontrado')
s=s.replace(old,new,1)
css='''\n.bi-topbar-nav{display:flex;align-items:center;justify-content:space-between;gap:24px}.bi-brand{min-width:0;flex:1}.top-nav{display:flex;align-items:center;justify-content:flex-end;gap:6px;flex-wrap:wrap}.top-nav-item{display:inline-flex;align-items:center;justify-content:center;padding:9px 12px;border-radius:9px;color:#CBD5E1!important;text-decoration:none!important;font-size:.68rem;font-weight:800;letter-spacing:.02em;white-space:nowrap;border:1px solid transparent;transition:.15s ease}.top-nav-item:hover{background:rgba(255,255,255,.09);color:white!important}.top-nav-item.active{background:white;color:#0F172A!important;border-color:rgba(255,255,255,.7);box-shadow:0 2px 8px rgba(0,0,0,.12)}\n@media(max-width:980px){.bi-topbar-nav{align-items:flex-start;flex-direction:column;gap:12px}.top-nav{justify-content:flex-start;width:100%}.top-nav-item{padding:8px 10px;font-size:.62rem}}\n@media(max-width:560px){.bi-topbar-nav{gap:10px}.top-nav{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.top-nav-item{width:100%;padding:8px 6px;font-size:.58rem}.top-nav-item:last-child{grid-column:span 2}.bi-brand p{font-size:.68rem!important}}\n'''
if '.bi-topbar-nav{' not in s:s=s.replace('</style>',css+'\n</style>',1)
p.write_text(s,encoding='utf-8')
