from pathlib import Path

path=Path('app.py')
s=path.read_text(encoding='utf-8')

insert='''\n\ndef weekly_rank_html(team,week_index):\n    ranked=[]\n    for x in team:\n        sales=x["semanas"][week_index] if week_index < len(x.get("semanas",[])) else 0\n        award=x["premios"][week_index] if week_index < len(x.get("premios",[])) else 0\n        ranked.append((x,sales,award))\n    ranked.sort(key=lambda item:(item[1],item[2]),reverse=True)\n    cards=[]\n    for pos,(x,sales,award) in enumerate(ranked,1):\n        cards.append(\n            f'<div class="weekly-rank-card"><div class="weekly-rank-pos">{pos}º</div>'\n            f'<div class="weekly-rank-name">{html.escape(str(x["vendedor"]))}</div>'\n            f'<div class="weekly-rank-sales"><strong>{sales}</strong><span>VENDAS</span></div>'\n            f'<div class="weekly-rank-award"><strong>{money(award)}</strong><span>SEMANAL</span></div></div>'\n        )\n    return '<div class="weekly-rank-list">'+''.join(cards)+'</div>'\n\ndef weekly_seller_history_html(x):\n    rows=[]\n    for i,sales in enumerate(x.get("semanas",[])):\n        award=x["premios"][i] if i < len(x.get("premios",[])) else 0\n        rows.append(f'<div class="weekly-history-row"><span>SEMANA {i+1}</span><strong>{sales} vendas</strong><b>{money(award)}</b></div>')\n    return (f'<div class="weekly-history"><div class="weekly-history-name">{html.escape(str(x["vendedor"]))}</div>'\n            +''.join(rows)+f'<div class="weekly-history-total"><span>TOTAL NO MÊS</span><strong>{x.get("vendas",0)} vendas</strong><b>{money(x.get("premio_total",0))}</b></div></div>')\n\ndef weekly_desktop_table(team,max_weeks):\n    rows=[]\n    for x in sorted(team,key=lambda z:(sum(z.get("semanas",[])),z.get("premio_total",0)),reverse=True):\n        cells=[f'<td class="weekly-name">{html.escape(str(x["vendedor"]))}</td>']\n        for i in range(max_weeks):\n            sales=x["semanas"][i] if i < len(x.get("semanas",[])) else 0\n            award=x["premios"][i] if i < len(x.get("premios",[])) else 0\n            cells.append(f'<td><strong>{sales}</strong><small>vendas</small></td><td><strong>{money(award)}</strong><small>valor</small></td>')\n        cells.append(f'<td><strong>{money(x.get("premio_total",0))}</strong></td>')\n        rows.append('<tr>'+''.join(cells)+'</tr>')\n    heads=['VENDEDOR']\n    for i in range(max_weeks):heads.extend([f'S{i+1} VENDAS',f'S{i+1} VALOR'])\n    heads.append('SEMANAIS ACUMULADOS')\n    return '<div class="weekly-desktop-table"><table><thead><tr>'+''.join(f'<th>{h}</th>' for h in heads)+'</tr></thead><tbody>'+''.join(rows)+'</tbody></table></div>'\n'''
anchor='\ndef projection_status_visual(projected_ratio, meta_value=None, projection_value=None):'
if 'def weekly_rank_html(' not in s:
    s=s.replace(anchor,insert+anchor,1)

old='''    elif area=="SEMANAL":\n        st.markdown('<div class="section">Acompanhamento semanal · segunda a domingo</div>',unsafe_allow_html=True)\n        if not team:st.warning("Nenhum vendedor local ativo.");return\n        max_weeks=max(len(x["semanas"]) for x in team); data=[]\n        for x in team:\n            row={"Vendedor":x["vendedor"]}\n            for i in range(max_weeks):row[f"Semana {i+1}"]=x["semanas"][i]; row[f"Semanal S{i+1}"]=money(x["premios"][i])\n            row["Semanais acumulados"]=money(x["premio_total"]); data.append(row)\n        st.dataframe(data,use_container_width=True,hide_index=True,height=520)\n'''
new='''    elif area=="SEMANAL":\n        st.markdown('<div class="section">Acompanhamento semanal · segunda a domingo</div>',unsafe_allow_html=True)\n        if not team:st.warning("Nenhum vendedor local ativo.");return\n        max_weeks=max(len(x.get("semanas",[])) for x in team)\n        week_labels=[f"SEMANA {i+1}" for i in range(max_weeks)]\n        selected_week=st.segmented_control("Semana",week_labels,default=week_labels[0],key="weekly_week_selector",label_visibility="collapsed") or week_labels[0]\n        week_index=week_labels.index(selected_week)\n        st.markdown(weekly_rank_html(team,week_index),unsafe_allow_html=True)\n        seller_options=[x["vendedor"] for x in sorted(team,key=lambda z:normalize_text(z["vendedor"]))]\n        selected_seller=st.selectbox("Ver histórico semanal do vendedor",["SELECIONE UM VENDEDOR"]+seller_options,key="weekly_seller_history")\n        if selected_seller!="SELECIONE UM VENDEDOR":\n            selected=next((x for x in team if x["vendedor"]==selected_seller),None)\n            if selected:st.markdown(weekly_seller_history_html(selected),unsafe_allow_html=True)\n        st.markdown(weekly_desktop_table(team,max_weeks),unsafe_allow_html=True)\n'''
if old not in s: raise SystemExit('bloco semanal atual nao encontrado')
s=s.replace(old,new,1)

css='''\n.weekly-rank-list{display:grid;gap:7px;margin:8px 0 12px}.weekly-rank-card{display:grid;grid-template-columns:42px minmax(160px,1fr) 120px 160px;align-items:center;gap:10px;background:white;border:1px solid var(--line);border-radius:11px;padding:10px 13px;box-shadow:0 2px 8px rgba(15,23,42,.035)}.weekly-rank-pos{font-weight:900;color:#475569;text-align:center}.weekly-rank-name{font-size:.78rem;font-weight:900;color:#0F172A;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.weekly-rank-sales,.weekly-rank-award{display:flex;flex-direction:column;align-items:flex-end}.weekly-rank-sales strong{font-size:1.25rem;color:#0F172A}.weekly-rank-award strong{font-size:1rem;color:#0F172A}.weekly-rank-sales span,.weekly-rank-award span{font-size:.52rem;font-weight:850;color:#64748B;margin-top:2px}.weekly-history{background:white;border:1px solid var(--line);border-radius:12px;padding:12px 14px;margin:8px 0 14px}.weekly-history-name{font-size:.82rem;font-weight:900;color:#0F172A;margin-bottom:8px}.weekly-history-row,.weekly-history-total{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px;align-items:center;padding:8px 0;border-top:1px solid #EEF2F7}.weekly-history-row span,.weekly-history-total span{font-size:.6rem;font-weight:850;color:#64748B}.weekly-history-row strong,.weekly-history-total strong{font-size:.76rem;color:#0F172A}.weekly-history-row b,.weekly-history-total b{text-align:right;font-size:.76rem;color:#0F172A}.weekly-history-total{background:#F8FAFC;margin:5px -6px -4px;padding:10px 6px;border-radius:8px}.weekly-desktop-table{overflow:auto;border:1px solid var(--line);border-radius:12px;background:white;margin-top:12px}.weekly-desktop-table table{border-collapse:collapse;width:100%;white-space:nowrap;font-size:.68rem}.weekly-desktop-table th{background:#0F172A;color:white;padding:8px;font-size:.6rem}.weekly-desktop-table td{padding:8px;border-right:1px solid #EEF2F7;border-bottom:1px solid #EEF2F7;text-align:center}.weekly-desktop-table td strong{display:block;font-size:.72rem}.weekly-desktop-table td small{font-size:.5rem;color:#94A3B8}.weekly-desktop-table .weekly-name{text-align:left;font-weight:850;position:sticky;left:0;background:white;z-index:1}\n@media(max-width:700px){.weekly-rank-list{gap:5px}.weekly-rank-card{grid-template-columns:28px minmax(0,1fr) 74px 104px;gap:5px;padding:7px 8px;border-radius:9px}.weekly-rank-pos{font-size:.68rem}.weekly-rank-name{font-size:.72rem}.weekly-rank-sales strong{font-size:1.06rem}.weekly-rank-award strong{font-size:.76rem}.weekly-rank-sales span,.weekly-rank-award span{font-size:.43rem}.weekly-history{padding:10px}.weekly-history-row,.weekly-history-total{grid-template-columns:.8fr 1fr 1fr;gap:6px;padding:7px 0}.weekly-history-row span,.weekly-history-total span{font-size:.52rem}.weekly-history-row strong,.weekly-history-total strong,.weekly-history-row b,.weekly-history-total b{font-size:.68rem}.weekly-desktop-table{display:none}}\n'''
style_end='\n</style>"""'
if '.weekly-rank-list{' not in s:
    s=s.replace(style_end,css+style_end,1)
path.write_text(s,encoding='utf-8')
# trigger